trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/'

parameters:
  - name: runTests
    displayName: Run tests
    type: boolean
    default: true

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/Team-4_QA-development.yaml
  - name: solutionFolder
    value: src/
  - name: projectName
    value: EPR.RegulatorService.Facade.API
  - name: projectFolder
    value: EPR.RegulatorService.Facade.API
  - name: testProjectFolder
    value: EPR.RegulatorService.Facade.UnitTests
  - name: sonarQubeProjectKey
    value: epr_regulator_service_facade
  - name: sonarQubeProjectName
    value: epr_regulator_service_facade
  - name: runNugetTasks
    value: true
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: main

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{parameters.runTests}}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
