trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/'

parameters:
  - name: runTests
    displayName: Run tests
    type: boolean
    default: true
  - name: sonarqubeInstance
    displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
    type: string
    default: 'SonarQubeLatest'
    values:
    - 'SonarQube'
    - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src/
  - name: projectName
    value: EPR.RegulatorService.Facade.API
  - name: projectFolder
    value: EPR.RegulatorService.Facade.API
  - name: testProjectFolder
    value: EPR.RegulatorService.Facade.UnitTests
  - name: sonarQubeProjectKey
    value: epr_regulator_service_facade
  - name: sonarQubeProjectName
    value: epr_regulator_service_facade
  - name: runNugetTasks
    value: true
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      ref: main
      endpoint: DEFRA

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{parameters.runTests}}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
    dotnetVersion: ${{ variables.dotnetVersion }}
