variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprregulatorfacadeendregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprregulatorfacadeendregistry'
  serviceName: 'prdrwdwebwa1406'
